version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=job_application_db
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  employee_formfilling:
    container_name: Employee_Formfilling
    build:
      context: ./Employee_Formfilling
      dockerfile: Dockerfile
    ports:
      - "7006:80"
    networks:
      - app-network
    restart: unless-stopped

  hr_formfilling:
    container_name: HR_FormFilling
    build:
      context: ./HR_FormFilling
      dockerfile: Dockerfile
    ports:
      - "7007:80"
    networks:
      - app-network
    restart: unless-stopped

  welcome_page:
    container_name: Welcome_Page
    build:
      context: ./Welcome-Page
      dockerfile: Dockerfile
    ports:
      - "7008:80"
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - "5003:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=job_application_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge

